baseURL = "https://childrenconcert.com/"
languageCode = "en-us"
title = "Children for Children"

disableKinds = ["taxonomy", "term" ]

############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "Performers"
URL = "#performers"
weight = 2

[[menu.main]]
name = "Our Cause"
URL = "#main"
weight = 3

[[menu.main]]
name = "Donation"
URL = "#donate"
weight = 4

######################## modules ####################################

[module]
[[module.imports]]
path = "github.com/sindresorhus/modern-normalize"
disable = false
[[module.imports.mounts]]
source = "./modern-normalize.css"
#target = "assets/scss/_modern-normalize.scss"
target = "static/css/modern-normalize.css"
