name: Hugo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get packages
        run: yarn

      - name: Get latest data
        run: node getPerformers.js

      - name: Build and Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.BUILD_TOKEN }}
